FROM hello-world:latest
LABEL maintainer="kylehlw@gmail.com"
WORKDIR /
wget -q --no-check-certificate https://publicshare.ventitechnologies.cn/independent/nv-tensorrt-repo-ubuntu2004-cuda11.6-trt8.4.1.5-ga-20220604_1-1_amd64.deb
